name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update
    - run: sudo apt -y install gcc-arm-none-eabi make
    - run: make -C src/step-0-minimal
    - run: make -C src/step-1-blinky
    - run: make -C src/step-2-systick
    - run: make -C src/step-3-uart
    - run: make -C src/step-4-printf
    - run: make -C src/step-5-format
    - run: make -C src/step-6-clock
    - run: make -C src/step-7-interrupt
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc-arm-embedded make
    - run: make -C src/step-0-minimal
    - run: make -C src/step-1-blinky
    - run: make -C src/step-2-systick
    - run: make -C src/step-3-uart
    - run: make -C src/step-4-printf
    - run: make -C src/step-5-format
    - run: make -C src/step-6-clock
    - run: make -C src/step-7-interrupt
